/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Santiago
 */
public class VistaUbicacion extends javax.swing.JPanel {

    /**
     * Creates new form VistaUbicacion
     */
    public VistaUbicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextPane2 = new javax.swing.JTextPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1024, 576));
        setMinimumSize(new java.awt.Dimension(1024, 576));
        setPreferredSize(new java.awt.Dimension(1024, 476));
        setLayout(null);

        jTextPane2.setEditable(false);
        jTextPane2.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jTextPane2.setText("El Hotel VASSA es un hotel en la Carrera 1 de Santa Marta, muy cerca de las famosas Playa Blanca y el centro Histórico de Santa Marta. Desde el hotel podrá visitar lugares como el acuario distrital, las playas Rodadero y Taganga, la bahía de Santa Marta o realizar un completo recorrido por el sector histórico de Santa Marta.\n\nAdemás, el hotel se encuentra a poca distancia del aeropuerto Simón Bolivar, la terminal de transporte terrestre y la zona industrial de Montecarlo, y es ideal para acercarse al centro comercial Plaza Central, Las Ferias, el centro de Santa Marta y el centro comercial Gran Portal. A solo 3.9km del sector Pozos Colorados.\n");
        add(jTextPane2);
        jTextPane2.setBounds(60, 180, 290, 270);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jTextPane1.setText("      Mejor Ubicación\n\nUbicada en una de las zonas más turísitcas de la ciudad, cerca de las playas Rodadero y Playa Blanca.\nKR 1 A # 26 - 37");
        add(jTextPane1);
        jTextPane1.setBounds(470, 230, 150, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Imagen_2.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/MAPA_HOTEL.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(400, 170, 560, 280);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
