package Vista;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import org.jdatepicker.JDatePicker;

public class VistaCancelacion extends javax.swing.JFrame {

    public VistaCancelacion() {
        initComponents();
        this.setTitle("Buscar Reservación");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.fondoTranslucido.setBackground(new Color(255, 255, 255, 180));
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        seleccionarPorDefecto();
        this.pack();
    }

    public final void seleccionarPorDefecto() {
        radioTelyFecha.setSelected(false);
        campoTelefono.setEnabled(false);
        fechaInicial.setEnabled(false);
        radioNombre.setSelected(true);
        campoNombre.setEnabled(true);
    }

    public JButton getBotonBuscar() {
        return botonBuscar;
    }

    public ButtonGroup getBotonesOpcion() {
        return botonesOpcion;
    }

    public JTextField getCampoNombre() {
        return campoNombre;
    }

    public JTextField getCampoTelefono() {
        return campoTelefono;
    }

    public JDatePicker getFechaInicial() {
        return fechaInicial;
    }

    public JRadioButton getRadioNombre() {
        return radioNombre;
    }

    public JRadioButton getRadioTelyFecha() {
        return radioTelyFecha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesOpcion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioTelyFecha = new javax.swing.JRadioButton();
        radioNombre = new javax.swing.JRadioButton();
        botonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        fechaInicial = new org.jdatepicker.JDatePicker();
        campoTelefono = new javax.swing.JTextField();
        fondoTranslucido = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(350, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(350, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radioTelyFecha.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        radioTelyFecha.setText("Telefono y Fecha Inicial");
        radioTelyFecha.setContentAreaFilled(false);
        radioTelyFecha.setFocusPainted(false);
        jPanel1.add(radioTelyFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 150, -1));

        radioNombre.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        radioNombre.setText("Nombre Completo");
        radioNombre.setContentAreaFilled(false);
        radioNombre.setFocusPainted(false);
        radioNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNombreActionPerformed(evt);
            }
        });
        jPanel1.add(radioNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, -1));

        botonBuscar.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        botonBuscar.setText("Buscar Reservación");
        botonBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonBuscar.setBorderPainted(false);
        botonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscar.setFocusPainted(false);
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 190, 40));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        jLabel1.setText("Buscar Reserva a Cancelar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, 30));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel2.setText("Seleccione 'Telefono y Fecha Inicial' si tiene varias reservas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 320, -1));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel5.setText("Nombre del Titular de la Reserva");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, -1));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel6.setText("Teléfono con el que Realizó la Reserva");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, -1));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel3.setText("Fecha De Inicio de la Reserva");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, -1));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel4.setText("Seleccione los datos con los que va a buscar la reservación");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 320, -1));

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        jPanel1.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, -1));

        fechaInicial.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fechaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 150, -1));
        jPanel1.add(campoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 150, -1));

        fondoTranslucido.setBackground(new java.awt.Color(255, 255, 255));
        fondoTranslucido.setMaximumSize(new java.awt.Dimension(310, 360));
        fondoTranslucido.setMinimumSize(new java.awt.Dimension(310, 360));
        fondoTranslucido.setOpaque(true);
        fondoTranslucido.setPreferredSize(new java.awt.Dimension(310, 360));
        jPanel1.add(fondoTranslucido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Fondo_Cancelacion.png"))); // NOI18N
        imagenFondo.setMaximumSize(new java.awt.Dimension(350, 400));
        imagenFondo.setMinimumSize(new java.awt.Dimension(350, 400));
        imagenFondo.setPreferredSize(new java.awt.Dimension(350, 400));
        jPanel1.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void radioNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCancelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCancelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCancelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCancelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCancelacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.ButtonGroup botonesOpcion;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private org.jdatepicker.JDatePicker fechaInicial;
    private javax.swing.JLabel fondoTranslucido;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioNombre;
    private javax.swing.JRadioButton radioTelyFecha;
    // End of variables declaration//GEN-END:variables
}
