package Vista;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import org.jdatepicker.JDatePicker;

public class VistaFormulario extends javax.swing.JFrame {

    public VistaFormulario() {
        initComponents();
        this.setTitle("Hacer una reservación");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.fondoTranslucido.setBackground(new Color(255, 255, 255, 95));
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    public JButton getBotonAgregar() {
        return botonAgregar;
    }

    public JButton getBotonConfirmarReserva() {
        return botonConfirmarReserva;
    }

    public JButton getBotonConsultar() {
        return botonConsultar;
    }

    public JButton getBotonLimpiar() {
        return botonLimpiar;
    }

    public JComboBox<String> getComboHabitaciones() {
        return comboHabitaciones;
    }

    public JComboBox<String> getComboPersonas() {
        return comboPersonas;
    }

    public JComboBox<String> getComboTipoHab() {
        return comboTipo;
    }

    public JDatePicker getFechaFinal() {
        return fechaFinal;
    }

    public JDatePicker getFechaInicial() {
        return fechaInicial;
    }

    public JLabel getNumHabDoblesReservadas() {
        return numHabDoblesReservadas;
    }

    public JLabel getNumHabSencillasReservadas() {
        return numHabSencillasReservadas;
    }

    public JTextField getNumId() {
        return numId;
    }

    public JLabel getNumPersonasReservadas() {
        return numPersonasReservadas;
    }

    public JComboBox<String> getComboTipoId() {
        return comboTipoId;
    }

    public JLabel getValorAproximado() {
        return valorAproximado;
    }

    public JLabel getValorDescuentos() {
        return valorDescuentos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboHabitaciones = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fechaFinal = new org.jdatepicker.JDatePicker();
        fechaInicial = new org.jdatepicker.JDatePicker();
        jLabel4 = new javax.swing.JLabel();
        comboPersonas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        numHabSencillasReservadas = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        numHabDoblesReservadas = new javax.swing.JLabel();
        numPersonasReservadas = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        valorAproximado = new javax.swing.JLabel();
        valorDescuentos = new javax.swing.JLabel();
        botonLimpiar = new javax.swing.JButton();
        botonConfirmarReserva = new javax.swing.JButton();
        botonConsultar = new javax.swing.JButton();
        comboTipoId = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        numId = new javax.swing.JTextField();
        fondoTranslucido = new javax.swing.JLabel();
        fondoFormulario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(380, 610));
        jPanel1.setMinimumSize(new java.awt.Dimension(380, 610));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboHabitaciones.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        comboHabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jPanel1.add(comboHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel3.setText("Hasta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 28, -1));

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabel1.setText("Asigna tu Reserva");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, -1));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel2.setText("Desde");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        jPanel1.add(fechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 80, -1));
        jPanel1.add(fechaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 90, -1));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel4.setText("Reservar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 44, -1));

        comboPersonas.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        comboPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel1.add(comboPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel5.setText("habitaciones");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        comboTipo.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sencilla", "Doble" }));
        jPanel1.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 71, -1));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel6.setText("Para");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel7.setText("personas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        botonAgregar.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        botonAgregar.setText("Agregar a la reserva");
        jPanel1.add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 131, -1));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel8.setText("Tu Reserva");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        numHabSencillasReservadas.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        numHabSencillasReservadas.setText("0");
        jPanel1.add(numHabSencillasReservadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 20, -1));

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel10.setText("Habitaciones Sencillas");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 104, -1));

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel11.setText("Habitaciones Dobles");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 110, -1));

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel12.setText("Personas");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        numHabDoblesReservadas.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        numHabDoblesReservadas.setText("0");
        jPanel1.add(numHabDoblesReservadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 20, -1));

        numPersonasReservadas.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        numPersonasReservadas.setText("0");
        jPanel1.add(numPersonasReservadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 20, -1));

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel14.setText("Valor Aproximado:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 90, -1));

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel15.setText("Total Descuentos:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 90, -1));

        valorAproximado.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        valorAproximado.setText("$0");
        jPanel1.add(valorAproximado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 110, -1));

        valorDescuentos.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        valorDescuentos.setText("$0");
        jPanel1.add(valorDescuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 90, -1));

        botonLimpiar.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(botonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 90, -1));

        botonConfirmarReserva.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        botonConfirmarReserva.setText("Confirmar Reserva");
        botonConfirmarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarReservaActionPerformed(evt);
            }
        });
        jPanel1.add(botonConfirmarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 170, 30));

        botonConsultar.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        botonConsultar.setText("Consultar Disponibilidad");
        botonConsultar.setToolTipText("");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(botonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 170, -1));

        comboTipoId.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        comboTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula de ciudadania", "Pasaporte", "Cedula de extranjeria" }));
        jPanel1.add(comboTipoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 130, -1));

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel9.setText("Tipo de Documento");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 495, 110, -1));

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jLabel13.setText("Número de identificacion");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 525, 190, -1));

        numId.setFont(new java.awt.Font("Nirmala UI", 0, 11)); // NOI18N
        jPanel1.add(numId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 130, -1));

        fondoTranslucido.setOpaque(true);
        jPanel1.add(fondoTranslucido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 320, 560));

        fondoFormulario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Fondo_Formulario.png"))); // NOI18N
        fondoFormulario.setName(""); // NOI18N
        jPanel1.add(fondoFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonConfirmarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConfirmarReservaActionPerformed

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonConfirmarReserva;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JComboBox<String> comboHabitaciones;
    private javax.swing.JComboBox<String> comboPersonas;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboTipoId;
    private org.jdatepicker.JDatePicker fechaFinal;
    private org.jdatepicker.JDatePicker fechaInicial;
    private javax.swing.JLabel fondoFormulario;
    private javax.swing.JLabel fondoTranslucido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numHabDoblesReservadas;
    private javax.swing.JLabel numHabSencillasReservadas;
    private javax.swing.JTextField numId;
    private javax.swing.JLabel numPersonasReservadas;
    private javax.swing.JLabel valorAproximado;
    private javax.swing.JLabel valorDescuentos;
    // End of variables declaration//GEN-END:variables
}
