/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 20-feb.-2021 11:08:07 a. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS cuenta CASCADE
;

DROP TABLE IF EXISTS cuenta_producto CASCADE
;

DROP TABLE IF EXISTS empleado CASCADE
;

DROP TABLE IF EXISTS habitacion CASCADE
;

DROP TABLE IF EXISTS habitacion_tipo CASCADE
;

DROP TABLE IF EXISTS huesped CASCADE
;

DROP TABLE IF EXISTS pago CASCADE
;

DROP TABLE IF EXISTS persona CASCADE
;

DROP TABLE IF EXISTS producto CASCADE
;

DROP TABLE IF EXISTS registro CASCADE
;

DROP TABLE IF EXISTS reserva CASCADE
;

DROP TABLE IF EXISTS reserva_habitacion CASCADE
;

DROP TABLE IF EXISTS tipo CASCADE
;

/* Create Tables */

CREATE TABLE cuenta
(
	k_id_cuenta integer NOT NULL,
	k_id_reserva integer NULL
)
;

CREATE TABLE cuenta_producto
(
	k_id_cuenta integer NULL,
	k_codigo integer NULL,
	q_cantidad integer NULL
)
;

CREATE TABLE empleado
(
	n_password varchar(50) NOT NULL,
	n_usuario varchar(20) NOT NULL,
	k_id_tipo integer NOT NULL,
	k_id_numero integer NOT NULL
)
;

CREATE TABLE habitacion
(
	k_id_habitacion smallint NOT NULL,
	"q_numCamas" smallint NOT NULL
)
;

CREATE TABLE habitacion_tipo
(
	k_id_habitacion smallint NULL,
	k_id_tipo smallint NULL
)
;

CREATE TABLE huesped
(
	k_id_tipo integer NOT NULL,
	k_id_numero integer NOT NULL,
	n_direccion varchar(150) NOT NULL,
	k_it_numero integer NOT NULL,
	q_telefono integer NOT NULL
)
;

CREATE TABLE pago
(
	k_id_pago integer NOT NULL,
	f_pago date NOT NULL,
	n_metodo smallint NULL,
	v_total numeric(12,2) NOT NULL,
	k_id_cuenta integer NULL
)
;

CREATE TABLE persona
(
	k_id_tipo integer NOT NULL,
	k_id_numero integer NOT NULL
)
;

CREATE TABLE producto
(
	k_codigo integer NOT NULL,
	v_precio numeric(12,2) NOT NULL,
	q_stock integer NOT NULL
)
;

CREATE TABLE registro
(
	"k_id_Registro" integer NOT NULL,
	f_checkout varchar(50) NULL,
	f_checkin varchar(50) NULL,
	k_id_tipo integer NULL,
	k_id_numero integer NULL,
	k_id_reserva integer NULL
)
;

CREATE TABLE reserva
(
	k_id_reserva integer NOT NULL,
	i_estado smallint NOT NULL,
	f_inicio date NOT NULL,
	f_final date NOT NULL,
	"q_numDias" smallint NOT NULL,
	k_id_tipo integer NULL,
	k_id_numero integer NULL
)
;

CREATE TABLE reserva_habitacion
(
	k_id_reserva integer NULL,
	k_id_habitacion smallint NULL
)
;

CREATE TABLE tipo
(
	k_id_tipo smallint NOT NULL,
	v_precio numeric(12,2) NOT NULL,
	v_descuento numeric(12,2) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cuenta ADD CONSTRAINT "PK_cuenta"
	PRIMARY KEY (k_id_cuenta)
;

CREATE INDEX "IXFK_cuenta_Reserva" ON cuenta (k_id_reserva ASC)
;

CREATE INDEX "IXFK_cuenta_producto_cuenta" ON cuenta_producto (k_id_cuenta ASC)
;

CREATE INDEX "IXFK_cuenta_producto_producto" ON cuenta_producto (k_codigo ASC)
;

ALTER TABLE empleado ADD CONSTRAINT "PK_empleado"
	PRIMARY KEY (k_id_tipo,k_id_numero)
;

CREATE INDEX "IXFK_empleado_Persona" ON empleado (k_id_tipo ASC,k_id_numero ASC)
;

ALTER TABLE habitacion ADD CONSTRAINT "PK_habitacion"
	PRIMARY KEY (k_id_habitacion)
;

CREATE INDEX "IXFK_habitacion_tipo_habitacion" ON habitacion_tipo (k_id_habitacion ASC)
;

CREATE INDEX "IXFK_habitacion_tipo_tipo" ON habitacion_tipo (k_id_tipo ASC)
;

ALTER TABLE huesped ADD CONSTRAINT "PK_huesped"
	PRIMARY KEY (k_id_tipo,k_id_numero)
;

CREATE INDEX "IXFK_huesped_Persona" ON huesped (k_id_tipo ASC,k_id_numero ASC)
;

ALTER TABLE pago ADD CONSTRAINT "PK_pago"
	PRIMARY KEY (k_id_pago)
;

CREATE INDEX "IXFK_pago_cuenta" ON pago (k_id_cuenta ASC)
;

ALTER TABLE persona ADD CONSTRAINT "PK_Persona"
	PRIMARY KEY (k_id_tipo,k_id_numero)
;

ALTER TABLE producto ADD CONSTRAINT "PK_producto"
	PRIMARY KEY (k_codigo)
;

ALTER TABLE registro ADD CONSTRAINT "PK_Registro"
	PRIMARY KEY ("k_id_Registro")
;

CREATE INDEX "IXFK_Registro_huesped" ON registro (k_id_tipo ASC,k_id_numero ASC)
;

CREATE INDEX "IXFK_Registro_Reserva" ON registro (k_id_reserva ASC)
;

ALTER TABLE reserva ADD CONSTRAINT "PK_Reserva"
	PRIMARY KEY (k_id_reserva)
;

CREATE INDEX "IXFK_Reserva_Persona" ON reserva (k_id_tipo ASC,k_id_numero ASC)
;

CREATE INDEX "IXFK_reserva_habitacion_habitacion" ON reserva_habitacion (k_id_habitacion ASC)
;

CREATE INDEX "IXFK_reserva_habitacion_reserva" ON reserva_habitacion (k_id_reserva ASC)
;

ALTER TABLE tipo ADD CONSTRAINT "PK_tipo"
	PRIMARY KEY (k_id_tipo)
;

/* Create Foreign Key Constraints */

ALTER TABLE cuenta ADD CONSTRAINT "FK_cuenta_Reserva"
	FOREIGN KEY (k_id_reserva) REFERENCES reserva (k_id_reserva) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cuenta_producto ADD CONSTRAINT "FK_cuenta_producto_cuenta"
	FOREIGN KEY (k_id_cuenta) REFERENCES cuenta (k_id_cuenta) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cuenta_producto ADD CONSTRAINT "FK_cuenta_producto_producto"
	FOREIGN KEY (k_codigo) REFERENCES producto (k_codigo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE empleado ADD CONSTRAINT "FK_empleado_Persona"
	FOREIGN KEY (k_id_tipo,k_id_numero) REFERENCES persona (k_id_tipo,k_id_numero) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE habitacion_tipo ADD CONSTRAINT "FK_habitacion_tipo_habitacion"
	FOREIGN KEY (k_id_habitacion) REFERENCES habitacion (k_id_habitacion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE habitacion_tipo ADD CONSTRAINT "FK_habitacion_tipo_tipo"
	FOREIGN KEY (k_id_tipo) REFERENCES tipo (k_id_tipo) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE huesped ADD CONSTRAINT "FK_huesped_Persona"
	FOREIGN KEY (k_id_tipo,k_id_numero) REFERENCES persona (k_id_tipo,k_id_numero) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE pago ADD CONSTRAINT "FK_pago_cuenta"
	FOREIGN KEY (k_id_cuenta) REFERENCES cuenta (k_id_cuenta) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE registro ADD CONSTRAINT "FK_Registro_huesped"
	FOREIGN KEY (k_id_tipo,k_id_numero) REFERENCES huesped (k_id_tipo,k_id_numero) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE registro ADD CONSTRAINT "FK_Registro_Reserva"
	FOREIGN KEY (k_id_reserva) REFERENCES reserva (k_id_reserva) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE reserva ADD CONSTRAINT "FK_Reserva_Persona"
	FOREIGN KEY (k_id_tipo,k_id_numero) REFERENCES persona (k_id_tipo,k_id_numero) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE reserva_habitacion ADD CONSTRAINT "FK_reserva_habitacion_habitacion"
	FOREIGN KEY (k_id_habitacion) REFERENCES habitacion (k_id_habitacion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE reserva_habitacion ADD CONSTRAINT "FK_reserva_habitacion_reserva"
	FOREIGN KEY (k_id_reserva) REFERENCES reserva (k_id_reserva) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE pago
	IS 'registra la forma y elc omo se finaliza el monto de pago de uso de servicios en el hotel por parte '
;

COMMENT ON TABLE persona
	IS 'Tabla que relaciona e identifica el tipo de tipo de cliente y el asigna un numero de cliente y de este se forma el identificador de cada persona '
;

COMMENT ON TABLE registro
	IS 'Entidad que registra la entrada y salida de los clientes al hotel'
;

COMMENT ON TABLE reserva
	IS 'metodo por el cual se realiza la reserva de una habitacion en el hotel, bien sea por parte de un empleado, o de un cliente del hotel '
;

COMMENT ON TABLE tipo
	IS 'define el tipo de habitacion y las clasifica  otorgandole un valor tarifario difernete'
;
