package Vista;

import javax.swing.JButton;

public class VistaMenu extends javax.swing.JPanel {

    public VistaMenu() {
        initComponents();
    }

    public JButton getBotonSalir() {
        return botonSalir;
    }

    public JButton getBotonLogin() {
        return botonLogin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonLogin = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(250, 300));
        setMinimumSize(new java.awt.Dimension(250, 300));
        setPreferredSize(new java.awt.Dimension(250, 300));
        setLayout(null);

        botonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Boton_Login.png"))); // NOI18N
        botonLogin.setBorderPainted(false);
        botonLogin.setContentAreaFilled(false);
        botonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLogin.setFocusPainted(false);
        botonLogin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Boton_Login_Hover.png"))); // NOI18N
        add(botonLogin);
        botonLogin.setBounds(0, 40, 250, 100);

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Boton_Salir.png"))); // NOI18N
        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.setFocusPainted(false);
        botonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Boton_Salir_Hover.png"))); // NOI18N
        add(botonSalir);
        botonSalir.setBounds(0, 140, 250, 100);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLogin;
    private javax.swing.JButton botonSalir;
    // End of variables declaration//GEN-END:variables
}
