/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Santiago
 */
public class VistaContacto extends javax.swing.JPanel {

    /**
     * Creates new form VistaContacto
     */
    public VistaContacto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextPane1 = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1024, 476));
        setMinimumSize(new java.awt.Dimension(1024, 476));
        setPreferredSize(new java.awt.Dimension(1024, 476));
        setLayout(null);

        jTextPane1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane1.setText("Conozca todos los datos de contacto de los establecimientos de Hoteles VASSA: email, teléfono, fax... y además tiene a su disposición un formulario web para enviarnos sus mensajes. \n\nReserve al mejor precio online garantizado, de forma directa con nuestros hoteles solo desde aquí, la web oficial de Hoteles VASSA.");
        jTextPane1.setOpaque(false);
        add(jTextPane1);
        jTextPane1.setBounds(50, 170, 230, 230);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setText("Sitio Web: Vassahoteles.com");
        add(jLabel8);
        jLabel8.setBounds(410, 150, 480, 80);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel7.setText("Email: Reservas@vassahotel.com");
        add(jLabel7);
        jLabel7.setBounds(410, 110, 480, 80);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setText("Telefonos: 01 8000 5467800 - (PBX) 547 1687");
        add(jLabel5);
        jLabel5.setBounds(410, 70, 540, 80);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setOpaque(true);
        add(jLabel6);
        jLabel6.setBounds(400, 80, 560, 140);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 255));
        jLabel3.setText("VASSAHotel");
        add(jLabel3);
        jLabel3.setBounds(160, 80, 130, 40);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contacto");
        add(jLabel2);
        jLabel2.setBounds(50, 80, 100, 40);

        jLabel1.setBackground(new java.awt.Color(0, 51, 153));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        add(jLabel1);
        jLabel1.setBounds(10, 10, 323, 454);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Imagen_3.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(350, 10, 660, 450);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
