/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 21-feb.-2021 9:06:31 a. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS cuenta CASCADE
;

DROP TABLE IF EXISTS cuenta_producto CASCADE
;

DROP TABLE IF EXISTS empleado CASCADE
;

DROP TABLE IF EXISTS habitacion CASCADE
;

DROP TABLE IF EXISTS habitacion_tipo CASCADE
;

DROP TABLE IF EXISTS huesped CASCADE
;

DROP TABLE IF EXISTS pago CASCADE
;

DROP TABLE IF EXISTS persona CASCADE
;

DROP TABLE IF EXISTS producto CASCADE
;

DROP TABLE IF EXISTS registro CASCADE
;

DROP TABLE IF EXISTS reserva CASCADE
;

DROP TABLE IF EXISTS reserva_habitacion CASCADE
;

DROP TABLE IF EXISTS tipo_habitacion CASCADE
;

/* Create Tables */

CREATE TABLE cuenta
(
	k_id_cuenta integer NOT NULL,	-- identificador de las cuentas que se generan al momento de realizar los registros en la reserva, y que relaciona los productos consumidos por lso huespedes, y permite liquidarla con lso pagos
	k_id_reserva integer NULL
)
;

CREATE TABLE cuenta_producto
(
	k_id_cuenta integer NULL,
	k_codigo integer NULL,
	q_cantidad integer NULL
)
;

CREATE TABLE empleado
(
	n_cargo varchar(20) NULL,	-- Nombre del cargo que se le asigna a un empleado en la empresa
	n_password varchar(15) NOT NULL,	-- registra la clave del emprelado previamente encriptado en un sha256
	n_usuario varchar(50) NOT NULL,	-- Registra e nombre de usario con el que queda registrado cada empleado en la base de datos y con el cuadual podra acceder a ella
	k_id_persona_tipo smallint NOT NULL,
	k_id_persona_numero integer NOT NULL
)
;

CREATE TABLE habitacion
(
	k_id_habitacion smallint NOT NULL,	-- Clave valor que identifica a cada una de las habitaciones en el sistema
	"q_numCamas " smallint NOT NULL	-- Registra el numero de camas que existen en cada habitacion
)
;

CREATE TABLE habitacion_tipo
(
	k_id_habitacion smallint NULL,
	k_id_tipo_habitacion smallint NULL
)
;

CREATE TABLE huesped
(
	k_id_persona_tipo smallint NOT NULL,
	"k_id_persona_ numero" integer NOT NULL,
	n_direccion_residencia varchar(150) NOT NULL,	-- Direccion de residencia del huesped
	n_ciudad_residencia varchar(50) NOT NULL,	-- Se consignara la cidad de residencia del huesped
	q_telefono integer NOT NULL,	-- numero de telefono del huesped que se registra en eel hortel
	f_fecha_nacimiento date NULL	-- fecha de nacimiento del huesped
)
;

CREATE TABLE pago
(
	k_id_pago integer NOT NULL,	-- clave valor que registra cada uno de los pagos generados por la entidad cuenta
	f_pago date NOT NULL,	-- fecha en la que se registra el pago de la cuenta en el sistema del banco
	n_metodo smallint NULL,	-- identifica la forma con que realiza cada pago
	v_total numeric(12,2) NOT NULL,	-- registra el valor total del pago con los descuentos aplicados
	k_id_cuenta integer NULL
)
;

CREATE TABLE persona
(
	k_id_persona_tipo smallint NOT NULL,	-- Clave valor o de un numero determinado Tipo de documento de identificación de la persona registrada en el hotel
	k_id_persona_numero integer NOT NULL,	-- clave valor que  busca capturar el Número de documento de identificación de la persona registrada.
	n_apellido varchar(30) NOT NULL,	-- Apellidos de la persona que se registara en el sistema
	n_nombre varchar(30) NOT NULL	-- Nombres de la persona que se registra en el sistema
)
;

CREATE TABLE producto
(
	"k_codigo " integer NOT NULL,	-- identifica cada uno de los productos para facturar en el sistema, valor que puede ser digitado por para realizar el registro de facturacion y movimiento de inventarios
	"v_precio " numeric(12,2) NOT NULL,	-- se consigna el valor individual de cada producto
	q_stock integer NOT NULL
)
;

CREATE TABLE registro
(
	"k_id_Registro" integer NOT NULL,	-- Clave valor de los registros de los huespedes en el hotel, en la fecha de entrada como de salida
	"f_checkin " date NULL,	-- Se registrara la la fecha en la cual el husped hace el ingreso al hotel validado en el rango de la fechas de la reserva 
	"f_checkout  " date NULL,	-- fecha de salida del huesped validado previamente que se halla registrado
	k_id_perosna_tipo smallint NULL,
	k_id_persona_numero integer NULL,
	k_id_reserva integer NULL
)
;

CREATE TABLE reserva
(
	k_id_reserva integer NOT NULL,	-- Clave valor que identifica todas las Reservas realizadas al hotel
	i_estado smallint NOT NULL,	-- Indica el estado de la reserva deacuerdo a un listado de opciones definidos en la capa de aplicacion
	f_inicio date NOT NULL,	-- Fecha en la que se inicia la reserva en el hotel
	"f_final " date NOT NULL,	-- fecha en la que el cliente indica hasta cuando desea hospedarce en el hotel, para validar la reserva
	"q_num_dias " smallint NOT NULL,	-- Atributo derivado entre f_inicio y f_final, que contabiliza el numero de dias que quedara registrado en la reserva
	k_id_perosna_tipo smallint NULL,
	k_id_persona_numero integer NULL
)
;

CREATE TABLE reserva_habitacion
(
	k_id_reserva integer NULL,
	k_id_habitacion smallint NULL
)
;

CREATE TABLE tipo_habitacion
(
	k_id_tipo_habitacion smallint NOT NULL,	-- clave valor que permite identificar de un listado de opciones el tipo de habitaciones del hotel que permita clasificar las habitaciones
	v_precio numeric(12,2) NOT NULL,	-- valor asignado por noche de el tipo de la habitacion 
	v_descuento numeric(12,2) NOT NULL	-- valor  entero que se calcular
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE cuenta ADD CONSTRAINT "PK_cuenta"
	PRIMARY KEY (k_id_cuenta)
;

CREATE INDEX "IXFK_cuenta_Reserva" ON cuenta (k_id_reserva ASC)
;

CREATE INDEX "IXFK_cuenta_producto_cuenta" ON cuenta_producto (k_id_cuenta ASC)
;

CREATE INDEX "IXFK_cuenta_producto_producto" ON cuenta_producto (k_codigo ASC)
;

ALTER TABLE empleado ADD CONSTRAINT "PK_empleado"
	PRIMARY KEY (k_id_persona_tipo,k_id_persona_numero)
;

CREATE INDEX "IXFK_empleado_Persona" ON empleado (k_id_persona_tipo ASC,k_id_persona_numero ASC)
;

ALTER TABLE habitacion ADD CONSTRAINT "PK_habitacion"
	PRIMARY KEY (k_id_habitacion)
;

CREATE INDEX "IXFK_habitacion_tipo_habitacion" ON habitacion_tipo (k_id_habitacion ASC)
;

CREATE INDEX "IXFK_habitacion_tipo_tipo" ON habitacion_tipo (k_id_tipo_habitacion ASC)
;

ALTER TABLE huesped ADD CONSTRAINT "PK_huesped"
	PRIMARY KEY (k_id_persona_tipo,"k_id_persona_ numero")
;

CREATE INDEX "IXFK_huesped_Persona" ON huesped (k_id_persona_tipo ASC,"k_id_persona_ numero" ASC)
;

ALTER TABLE pago ADD CONSTRAINT "PK_pago"
	PRIMARY KEY (k_id_pago)
;

CREATE INDEX "IXFK_pago_cuenta" ON pago (k_id_cuenta ASC)
;

ALTER TABLE persona ADD CONSTRAINT "PK_Persona"
	PRIMARY KEY (k_id_persona_tipo,k_id_persona_numero)
;

ALTER TABLE producto ADD CONSTRAINT "PK_producto"
	PRIMARY KEY ("k_codigo ")
;

ALTER TABLE registro ADD CONSTRAINT "PK_Registro"
	PRIMARY KEY ("k_id_Registro")
;

CREATE INDEX "IXFK_Registro_huesped" ON registro (k_id_perosna_tipo ASC,k_id_persona_numero ASC)
;

CREATE INDEX "IXFK_Registro_Reserva" ON registro (k_id_reserva ASC)
;

ALTER TABLE reserva ADD CONSTRAINT "PK_Reserva"
	PRIMARY KEY (k_id_reserva)
;

CREATE INDEX "IXFK_Reserva_Persona" ON reserva (k_id_perosna_tipo ASC,k_id_persona_numero ASC)
;

CREATE INDEX "IXFK_reserva_habitacion_habitacion" ON reserva_habitacion (k_id_habitacion ASC)
;

CREATE INDEX "IXFK_reserva_habitacion_reserva" ON reserva_habitacion (k_id_reserva ASC)
;

ALTER TABLE tipo_habitacion ADD CONSTRAINT "PK_tipo"
	PRIMARY KEY (k_id_tipo_habitacion)
;

/* Create Foreign Key Constraints */

ALTER TABLE cuenta ADD CONSTRAINT "FK_cuenta_Reserva"
	FOREIGN KEY (k_id_reserva) REFERENCES reserva (k_id_reserva) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cuenta_producto ADD CONSTRAINT "FK_cuenta_producto_cuenta"
	FOREIGN KEY (k_id_cuenta) REFERENCES cuenta (k_id_cuenta) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE cuenta_producto ADD CONSTRAINT "FK_cuenta_producto_producto"
	FOREIGN KEY (k_codigo) REFERENCES producto ("k_codigo ") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE empleado ADD CONSTRAINT "FK_empleado_Persona"
	FOREIGN KEY (k_id_persona_tipo,k_id_persona_numero) REFERENCES persona (k_id_persona_tipo,k_id_persona_numero) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE habitacion_tipo ADD CONSTRAINT "FK_habitacion_tipo_habitacion"
	FOREIGN KEY (k_id_habitacion) REFERENCES habitacion (k_id_habitacion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE habitacion_tipo ADD CONSTRAINT "FK_habitacion_tipo_tipo"
	FOREIGN KEY (k_id_tipo_habitacion) REFERENCES tipo_habitacion (k_id_tipo_habitacion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE huesped ADD CONSTRAINT "FK_huesped_Persona"
	FOREIGN KEY (k_id_persona_tipo,"k_id_persona_ numero") REFERENCES persona (k_id_persona_tipo,k_id_persona_numero) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE pago ADD CONSTRAINT "FK_pago_cuenta"
	FOREIGN KEY (k_id_cuenta) REFERENCES cuenta (k_id_cuenta) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE registro ADD CONSTRAINT "FK_Registro_huesped"
	FOREIGN KEY (k_id_perosna_tipo,k_id_persona_numero) REFERENCES huesped (k_id_persona_tipo,"k_id_persona_ numero") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE registro ADD CONSTRAINT "FK_Registro_Reserva"
	FOREIGN KEY (k_id_reserva) REFERENCES reserva (k_id_reserva) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE reserva ADD CONSTRAINT "FK_Reserva_Persona"
	FOREIGN KEY (k_id_perosna_tipo,k_id_persona_numero) REFERENCES persona (k_id_persona_tipo,k_id_persona_numero) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE reserva_habitacion ADD CONSTRAINT "FK_reserva_habitacion_habitacion"
	FOREIGN KEY (k_id_habitacion) REFERENCES habitacion (k_id_habitacion) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE reserva_habitacion ADD CONSTRAINT "FK_reserva_habitacion_reserva"
	FOREIGN KEY (k_id_reserva) REFERENCES reserva (k_id_reserva) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE cuenta
	IS 'Entidad que relaciona los prodcutos consumidos por los clientes '
;

COMMENT ON COLUMN cuenta.k_id_cuenta
	IS 'identificador de las cuentas que se generan al momento de realizar los registros en la reserva, y que relaciona los productos consumidos por lso huespedes, y permite liquidarla con lso pagos'
;

COMMENT ON TABLE empleado
	IS 'Tabla que relaciona e identifica el tipo  de cliente y el asigna un numero de cliente y de este forma el identificador de cada persona'
;

COMMENT ON COLUMN empleado.n_cargo
	IS 'Nombre del cargo que se le asigna a un empleado en la empresa'
;

COMMENT ON COLUMN empleado.n_password
	IS 'registra la clave del emprelado previamente encriptado en un sha256'
;

COMMENT ON COLUMN empleado.n_usuario
	IS 'Registra e nombre de usario con el que queda registrado cada empleado en la base de datos y con el cuadual podra acceder a ella'
;

COMMENT ON TABLE habitacion
	IS 'registra las habitaciones existentes en el hotel'
;

COMMENT ON COLUMN habitacion.k_id_habitacion
	IS 'Clave valor que identifica a cada una de las habitaciones en el sistema'
;

COMMENT ON COLUMN habitacion."q_numCamas "
	IS 'Registra el numero de camas que existen en cada habitacion'
;

COMMENT ON TABLE huesped
	IS 'Tabla en la que se registraran a todos los huespedes que se alojen en el hotel'
;

COMMENT ON COLUMN huesped.n_direccion_residencia
	IS 'Direccion de residencia del huesped'
;

COMMENT ON COLUMN huesped.n_ciudad_residencia
	IS 'Se consignara la cidad de residencia del huesped'
;

COMMENT ON COLUMN huesped.q_telefono
	IS 'numero de telefono del huesped que se registra en eel hortel'
;

COMMENT ON COLUMN huesped.f_fecha_nacimiento
	IS 'fecha de nacimiento del huesped'
;

COMMENT ON TABLE pago
	IS 'registra la forma y elc omo se finaliza el monto de pago de uso de servicios en el hotel por parte '
;

COMMENT ON COLUMN pago.k_id_pago
	IS 'clave valor que registra cada uno de los pagos generados por la entidad cuenta'
;

COMMENT ON COLUMN pago.f_pago
	IS 'fecha en la que se registra el pago de la cuenta en el sistema del banco'
;

COMMENT ON COLUMN pago.n_metodo
	IS 'identifica la forma con que realiza cada pago'
;

COMMENT ON COLUMN pago.v_total
	IS 'registra el valor total del pago con los descuentos aplicados'
;

COMMENT ON TABLE persona
	IS 'Tabla que relaciona e identifica el tipo de tipo de cliente y el asigna un numero de cliente y de este se forma el identificador de cada persona '
;

COMMENT ON COLUMN persona.k_id_persona_tipo
	IS 'Clave valor o de un numero determinado Tipo de documento de identificación de la persona registrada en el hotel'
;

COMMENT ON COLUMN persona.k_id_persona_numero
	IS 'clave valor que  busca capturar el Número de documento de identificación de la persona registrada.'
;

COMMENT ON COLUMN persona.n_apellido
	IS 'Apellidos de la persona que se registara en el sistema'
;

COMMENT ON COLUMN persona.n_nombre
	IS 'Nombres de la persona que se registra en el sistema'
;

COMMENT ON TABLE producto
	IS 'entidad que relaciona los prodcutos que dispone el hotel para el uso y consumo de sus clientes para facturar'
;

COMMENT ON COLUMN producto."k_codigo "
	IS 'identifica cada uno de los productos para facturar en el sistema, valor que puede ser digitado por para realizar el registro de facturacion y movimiento de inventarios'
;

COMMENT ON COLUMN producto."v_precio "
	IS 'se consigna el valor individual de cada producto'
;

COMMENT ON TABLE registro
	IS 'Entidad que registra la entrada y salida de los clientes al hotel'
;

COMMENT ON COLUMN registro."k_id_Registro"
	IS 'Clave valor de los registros de los huespedes en el hotel, en la fecha de entrada como de salida'
;

COMMENT ON COLUMN registro."f_checkin "
	IS 'Se registrara la la fecha en la cual el husped hace el ingreso al hotel validado en el rango de la fechas de la reserva '
;

COMMENT ON COLUMN registro."f_checkout  "
	IS 'fecha de salida del huesped validado previamente que se halla registrado'
;

COMMENT ON TABLE reserva
	IS 'metodo por el cual se realiza la reserva de una habitacion en el hotel, bien sea por parte de un empleado, o de un cliente del hotel '
;

COMMENT ON COLUMN reserva.k_id_reserva
	IS 'Clave valor que identifica todas las Reservas realizadas al hotel'
;

COMMENT ON COLUMN reserva.i_estado
	IS 'Indica el estado de la reserva deacuerdo a un listado de opciones definidos en la capa de aplicacion'
;

COMMENT ON COLUMN reserva.f_inicio
	IS 'Fecha en la que se inicia la reserva en el hotel'
;

COMMENT ON COLUMN reserva."f_final "
	IS 'fecha en la que el cliente indica hasta cuando desea hospedarce en el hotel, para validar la reserva'
;

COMMENT ON COLUMN reserva."q_num_dias "
	IS 'Atributo derivado entre f_inicio y f_final, que contabiliza el numero de dias que quedara registrado en la reserva'
;

COMMENT ON TABLE tipo_habitacion
	IS 'define el tipo de habitacion y las clasifica  otorgandole un valor tarifario difernete'
;

COMMENT ON COLUMN tipo_habitacion.k_id_tipo_habitacion
	IS 'clave valor que permite identificar de un listado de opciones el tipo de habitaciones del hotel que permita clasificar las habitaciones'
;

COMMENT ON COLUMN tipo_habitacion.v_precio
	IS 'valor asignado por noche de el tipo de la habitacion '
;

COMMENT ON COLUMN tipo_habitacion.v_descuento
	IS 'valor  entero que se calcular'
;
